apiVersion: v1
kind: Service
metadata:
  name: forensics-service
  namespace: digital-forensics
spec:
  selector:
    app: forensics
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: ClusterIP
